### ISSUE TITLE
Automatizzazione Codici prodotti

### ISSUE THREAD

**Issue by GiulioGar** [GiulioGar/attimifanshop#5]
Cercare un plug in che consenta di automatizzare la creazione e l'inserimento dei codici prodotto

**Comment by sommopeppe** [comment]
utilizzare la funzionalità esporta e importa di woocommerce sui prodotti, è la soluzione migliore

**Comment by sommopeppe** [comment]
anche se non è piu' necessario inserire il codice prodotto quindi la funzione è utile per la modifica massiva di pezzi in magazzino e prezzi ma per il codice prodotto diventa inutile
