### ISSUE TITLE
Verifica funzionamento codici prodotto

### ISSUE THREAD

**Issue by GiulioGar** [GiulioGar/attimifanshop#6]
Verificare il funzionamento dei codici prodotti in magazzino, come funziona la gestione e come gestire gli stessi

**Comment by sommopeppe** [comment]
non bisogna aggiungere nessun codice prodotto o comunque sarà ininfluente, ho creato uno script custom che scala tutte le maglie della taglia e del colore ordinate indipendentemente dalla stampa
